
language: python
python:
  - "3.6"
env:
  global:
    - CC_TEST_REPORTER_ID=b42f01c176a6247bceb928ed6c66c8e882a3baaf17359b393c095721cb4cdef6

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c 'create database Book-A-Meal;' -U postgres
  - psql -c 'create database Book-A-Meal_test_db;' -U postgres


script:
  - pytest --cov=app/
  - coverage report


# generate code climate report
after_script:
  - codeclimate-test-reporter
  - coveralls

after_success:
  - coveralls
