
language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls


# command to run tests
script:
  - nose --with-coverage --cover-erase --cover-package app
  - coverage report


# generate code climate report
after_script:
  - codeclimate-test-reporter
  - coveralls

# push report to coveralls.io
after_success:
  - coveralls

#  language: python
#  python:
#    - "3.5.2"
#  install:
#    - pip install -r requirements.txt
#    - pip install coverage
#    - pip install coveralls
#  script:
#    - nosetests --with-coverage
#  after_success:
#- coveralls