
language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c 'test_db;' -U postgres -P '13811923'
# command to run tests

script:
  - pytest --cov=app/
  - coverage report


# generate code climate report
after_script:
  - codeclimate-test-reporter
  - coveralls

after_success:
  - coveralls
