"""empty message

Revision ID: 93501712dc02
Revises: 
Create Date: 2018-07-08 21:48:57.237680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93501712dc02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_info')
    op.drop_table('users')
    op.drop_table('menus')
    op.drop_table('meals')
    op.drop_table('caterers')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('order_cleared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['users.id'], name='orders_customer_fkey'),
    sa.ForeignKeyConstraint(['meal'], ['menus.id'], name='orders_meal_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    op.create_table('caterers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('caterers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users_info.user_id'], name='caterers_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='caterers_pkey'),
    sa.UniqueConstraint('email', name='caterers_email_key'),
    sa.UniqueConstraint('username', name='caterers_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('meals',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('meals_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('caterer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caterer'], ['caterers.id'], name='meals_caterer_fkey'),
    sa.PrimaryKeyConstraint('id', name='meals_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('menus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('caterer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meal'], ['meals.id'], name='menus_meal_fkey'),
    sa.PrimaryKeyConstraint('id', name='menus_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users_info.user_id'], name='users_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('users_info',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('user_counter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_info_pkey'),
    sa.UniqueConstraint('email', name='users_info_email_key')
    )
    # ### end Alembic commands ###
